pipeline {
    // agent any
    agent {
        dockerfile {
            dir 'src/'
            args '--platform=linux/amd64'// -v ${WORKSPACE}:/usr/src -v ${JOB_BASE_NAME}:/usr/src/node_modules'
        }
    }
    environment {
        HOME='.'
        HEADLESS=1
    }
    stages {
        stage('Env variables'){
            steps {
                sh "env"
            }
        }
        stage('Prep') {
            steps {
                dir('src'){
                    sh 'npm install'
//                     stash includes: 'node_modules', name: 'node_modules'
                }
            }
        }
        stage('Test') {
            steps {
                dir('src'){
                    sh 'node --version'
                    sh 'pwd'
                    sh 'ls'
                    sh "npm run wdio-headless"
                }

            }
        }
    }
}
