pipeline {
    agent any
    environment {
        HOME='.'
        HEADLESS=1
    }
    stages {
        stage('Env variables'){
            steps {
                sh "env"
            }
        }
        stage('Test') {
            steps {
                dir('src'){
                    sh 'pwd'
                    sh 'ls'
                    sh "docker run --name ${BUILD_TAG} --platform=linux/amd64 -v ${WORKSPACE}/src:/usr/src -v node_modules_${JOB_BASE_NAME}:/usr/src/node_modules -w /usr/src duquesnay/wdiobase:1.0 bash -c \"npm install && npm run wdio-headless\""
                }

            }
        }
    }
}
